# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_kernel_2mm_wrapper_0_0/zedboard_base_kernel_2mm_wrapper_0_0.xci
# IP: The module: 'zedboard_base_kernel_2mm_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_kernel_2mm_wrapper_0_0/constraints/kernel_2mm_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_kernel_2mm_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_kernel_2mm_wrapper_0_0/zedboard_base_kernel_2mm_wrapper_0_0.xci
# IP: The module: 'zedboard_base_kernel_2mm_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_kernel_2mm_wrapper_0_0/constraints/kernel_2mm_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_kernel_2mm_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
