// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// for_control
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of A_AXI
//        bit 31~0 - A_AXI[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of B_AXI
//        bit 31~0 - B_AXI[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of C_AXI
//        bit 31~0 - C_AXI[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of D_input_AXI
//        bit 31~0 - D_input_AXI[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of D_output_AXI
//        bit 31~0 - D_output_AXI[31:0] (Read/Write)
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_AP_CTRL           0x00
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_GIE               0x04
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_IER               0x08
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_ISR               0x0c
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_A_AXI_DATA        0x10
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_BITS_A_AXI_DATA        32
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_B_AXI_DATA        0x18
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_BITS_B_AXI_DATA        32
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_C_AXI_DATA        0x20
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_BITS_C_AXI_DATA        32
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_D_INPUT_AXI_DATA  0x28
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_BITS_D_INPUT_AXI_DATA  32
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_ADDR_D_OUTPUT_AXI_DATA 0x30
#define XKERNEL_2MM_WRAPPER_FOR_CONTROL_BITS_D_OUTPUT_AXI_DATA 32

