-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.2 (lin64) Build 2258646 Thu Jun 14 20:02:38 MDT 2018
-- Date        : Tue Sep  3 11:07:59 2019
-- Host        : tingyuan-OptiPlex-9010 running 64-bit Ubuntu 18.04.2 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_kernel_2mm_wrapper_0_0/zedboard_base_kernel_2mm_wrapper_0_0_stub.vhdl
-- Design      : zedboard_base_kernel_2mm_wrapper_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg484-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity zedboard_base_kernel_2mm_wrapper_0_0 is
  Port ( 
    s_axi_for_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_for_control_AWVALID : in STD_LOGIC;
    s_axi_for_control_AWREADY : out STD_LOGIC;
    s_axi_for_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_for_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_for_control_WVALID : in STD_LOGIC;
    s_axi_for_control_WREADY : out STD_LOGIC;
    s_axi_for_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_for_control_BVALID : out STD_LOGIC;
    s_axi_for_control_BREADY : in STD_LOGIC;
    s_axi_for_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_for_control_ARVALID : in STD_LOGIC;
    s_axi_for_control_ARREADY : out STD_LOGIC;
    s_axi_for_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_for_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_for_control_RVALID : out STD_LOGIC;
    s_axi_for_control_RREADY : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_gmem0_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem0_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem0_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_AWVALID : out STD_LOGIC;
    m_axi_gmem0_AWREADY : in STD_LOGIC;
    m_axi_gmem0_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem0_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_WLAST : out STD_LOGIC;
    m_axi_gmem0_WVALID : out STD_LOGIC;
    m_axi_gmem0_WREADY : in STD_LOGIC;
    m_axi_gmem0_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_BVALID : in STD_LOGIC;
    m_axi_gmem0_BREADY : out STD_LOGIC;
    m_axi_gmem0_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem0_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem0_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem0_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem0_ARVALID : out STD_LOGIC;
    m_axi_gmem0_ARREADY : in STD_LOGIC;
    m_axi_gmem0_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem0_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem0_RLAST : in STD_LOGIC;
    m_axi_gmem0_RVALID : in STD_LOGIC;
    m_axi_gmem0_RREADY : out STD_LOGIC;
    m_axi_gmem1_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem1_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem1_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_AWVALID : out STD_LOGIC;
    m_axi_gmem1_AWREADY : in STD_LOGIC;
    m_axi_gmem1_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem1_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_WLAST : out STD_LOGIC;
    m_axi_gmem1_WVALID : out STD_LOGIC;
    m_axi_gmem1_WREADY : in STD_LOGIC;
    m_axi_gmem1_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_BVALID : in STD_LOGIC;
    m_axi_gmem1_BREADY : out STD_LOGIC;
    m_axi_gmem1_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem1_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem1_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem1_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem1_ARVALID : out STD_LOGIC;
    m_axi_gmem1_ARREADY : in STD_LOGIC;
    m_axi_gmem1_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem1_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem1_RLAST : in STD_LOGIC;
    m_axi_gmem1_RVALID : in STD_LOGIC;
    m_axi_gmem1_RREADY : out STD_LOGIC;
    m_axi_gmem2_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem2_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_AWVALID : out STD_LOGIC;
    m_axi_gmem2_AWREADY : in STD_LOGIC;
    m_axi_gmem2_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_WLAST : out STD_LOGIC;
    m_axi_gmem2_WVALID : out STD_LOGIC;
    m_axi_gmem2_WREADY : in STD_LOGIC;
    m_axi_gmem2_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_BVALID : in STD_LOGIC;
    m_axi_gmem2_BREADY : out STD_LOGIC;
    m_axi_gmem2_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem2_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem2_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem2_ARVALID : out STD_LOGIC;
    m_axi_gmem2_ARREADY : in STD_LOGIC;
    m_axi_gmem2_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem2_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem2_RLAST : in STD_LOGIC;
    m_axi_gmem2_RVALID : in STD_LOGIC;
    m_axi_gmem2_RREADY : out STD_LOGIC;
    m_axi_gmem3_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem3_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem3_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_AWVALID : out STD_LOGIC;
    m_axi_gmem3_AWREADY : in STD_LOGIC;
    m_axi_gmem3_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem3_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_WLAST : out STD_LOGIC;
    m_axi_gmem3_WVALID : out STD_LOGIC;
    m_axi_gmem3_WREADY : in STD_LOGIC;
    m_axi_gmem3_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_BVALID : in STD_LOGIC;
    m_axi_gmem3_BREADY : out STD_LOGIC;
    m_axi_gmem3_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem3_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem3_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem3_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem3_ARVALID : out STD_LOGIC;
    m_axi_gmem3_ARREADY : in STD_LOGIC;
    m_axi_gmem3_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem3_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem3_RLAST : in STD_LOGIC;
    m_axi_gmem3_RVALID : in STD_LOGIC;
    m_axi_gmem3_RREADY : out STD_LOGIC;
    m_axi_gmem4_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem4_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem4_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem4_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem4_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_AWVALID : out STD_LOGIC;
    m_axi_gmem4_AWREADY : in STD_LOGIC;
    m_axi_gmem4_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem4_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_WLAST : out STD_LOGIC;
    m_axi_gmem4_WVALID : out STD_LOGIC;
    m_axi_gmem4_WREADY : in STD_LOGIC;
    m_axi_gmem4_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_BVALID : in STD_LOGIC;
    m_axi_gmem4_BREADY : out STD_LOGIC;
    m_axi_gmem4_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem4_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_gmem4_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem4_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_gmem4_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_gmem4_ARVALID : out STD_LOGIC;
    m_axi_gmem4_ARREADY : in STD_LOGIC;
    m_axi_gmem4_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_gmem4_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_gmem4_RLAST : in STD_LOGIC;
    m_axi_gmem4_RVALID : in STD_LOGIC;
    m_axi_gmem4_RREADY : out STD_LOGIC
  );

end zedboard_base_kernel_2mm_wrapper_0_0;

architecture stub of zedboard_base_kernel_2mm_wrapper_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "s_axi_for_control_AWADDR[5:0],s_axi_for_control_AWVALID,s_axi_for_control_AWREADY,s_axi_for_control_WDATA[31:0],s_axi_for_control_WSTRB[3:0],s_axi_for_control_WVALID,s_axi_for_control_WREADY,s_axi_for_control_BRESP[1:0],s_axi_for_control_BVALID,s_axi_for_control_BREADY,s_axi_for_control_ARADDR[5:0],s_axi_for_control_ARVALID,s_axi_for_control_ARREADY,s_axi_for_control_RDATA[31:0],s_axi_for_control_RRESP[1:0],s_axi_for_control_RVALID,s_axi_for_control_RREADY,ap_clk,ap_rst_n,interrupt,m_axi_gmem0_AWADDR[31:0],m_axi_gmem0_AWLEN[7:0],m_axi_gmem0_AWSIZE[2:0],m_axi_gmem0_AWBURST[1:0],m_axi_gmem0_AWLOCK[1:0],m_axi_gmem0_AWREGION[3:0],m_axi_gmem0_AWCACHE[3:0],m_axi_gmem0_AWPROT[2:0],m_axi_gmem0_AWQOS[3:0],m_axi_gmem0_AWVALID,m_axi_gmem0_AWREADY,m_axi_gmem0_WDATA[31:0],m_axi_gmem0_WSTRB[3:0],m_axi_gmem0_WLAST,m_axi_gmem0_WVALID,m_axi_gmem0_WREADY,m_axi_gmem0_BRESP[1:0],m_axi_gmem0_BVALID,m_axi_gmem0_BREADY,m_axi_gmem0_ARADDR[31:0],m_axi_gmem0_ARLEN[7:0],m_axi_gmem0_ARSIZE[2:0],m_axi_gmem0_ARBURST[1:0],m_axi_gmem0_ARLOCK[1:0],m_axi_gmem0_ARREGION[3:0],m_axi_gmem0_ARCACHE[3:0],m_axi_gmem0_ARPROT[2:0],m_axi_gmem0_ARQOS[3:0],m_axi_gmem0_ARVALID,m_axi_gmem0_ARREADY,m_axi_gmem0_RDATA[31:0],m_axi_gmem0_RRESP[1:0],m_axi_gmem0_RLAST,m_axi_gmem0_RVALID,m_axi_gmem0_RREADY,m_axi_gmem1_AWADDR[31:0],m_axi_gmem1_AWLEN[7:0],m_axi_gmem1_AWSIZE[2:0],m_axi_gmem1_AWBURST[1:0],m_axi_gmem1_AWLOCK[1:0],m_axi_gmem1_AWREGION[3:0],m_axi_gmem1_AWCACHE[3:0],m_axi_gmem1_AWPROT[2:0],m_axi_gmem1_AWQOS[3:0],m_axi_gmem1_AWVALID,m_axi_gmem1_AWREADY,m_axi_gmem1_WDATA[31:0],m_axi_gmem1_WSTRB[3:0],m_axi_gmem1_WLAST,m_axi_gmem1_WVALID,m_axi_gmem1_WREADY,m_axi_gmem1_BRESP[1:0],m_axi_gmem1_BVALID,m_axi_gmem1_BREADY,m_axi_gmem1_ARADDR[31:0],m_axi_gmem1_ARLEN[7:0],m_axi_gmem1_ARSIZE[2:0],m_axi_gmem1_ARBURST[1:0],m_axi_gmem1_ARLOCK[1:0],m_axi_gmem1_ARREGION[3:0],m_axi_gmem1_ARCACHE[3:0],m_axi_gmem1_ARPROT[2:0],m_axi_gmem1_ARQOS[3:0],m_axi_gmem1_ARVALID,m_axi_gmem1_ARREADY,m_axi_gmem1_RDATA[31:0],m_axi_gmem1_RRESP[1:0],m_axi_gmem1_RLAST,m_axi_gmem1_RVALID,m_axi_gmem1_RREADY,m_axi_gmem2_AWADDR[31:0],m_axi_gmem2_AWLEN[7:0],m_axi_gmem2_AWSIZE[2:0],m_axi_gmem2_AWBURST[1:0],m_axi_gmem2_AWLOCK[1:0],m_axi_gmem2_AWREGION[3:0],m_axi_gmem2_AWCACHE[3:0],m_axi_gmem2_AWPROT[2:0],m_axi_gmem2_AWQOS[3:0],m_axi_gmem2_AWVALID,m_axi_gmem2_AWREADY,m_axi_gmem2_WDATA[31:0],m_axi_gmem2_WSTRB[3:0],m_axi_gmem2_WLAST,m_axi_gmem2_WVALID,m_axi_gmem2_WREADY,m_axi_gmem2_BRESP[1:0],m_axi_gmem2_BVALID,m_axi_gmem2_BREADY,m_axi_gmem2_ARADDR[31:0],m_axi_gmem2_ARLEN[7:0],m_axi_gmem2_ARSIZE[2:0],m_axi_gmem2_ARBURST[1:0],m_axi_gmem2_ARLOCK[1:0],m_axi_gmem2_ARREGION[3:0],m_axi_gmem2_ARCACHE[3:0],m_axi_gmem2_ARPROT[2:0],m_axi_gmem2_ARQOS[3:0],m_axi_gmem2_ARVALID,m_axi_gmem2_ARREADY,m_axi_gmem2_RDATA[31:0],m_axi_gmem2_RRESP[1:0],m_axi_gmem2_RLAST,m_axi_gmem2_RVALID,m_axi_gmem2_RREADY,m_axi_gmem3_AWADDR[31:0],m_axi_gmem3_AWLEN[7:0],m_axi_gmem3_AWSIZE[2:0],m_axi_gmem3_AWBURST[1:0],m_axi_gmem3_AWLOCK[1:0],m_axi_gmem3_AWREGION[3:0],m_axi_gmem3_AWCACHE[3:0],m_axi_gmem3_AWPROT[2:0],m_axi_gmem3_AWQOS[3:0],m_axi_gmem3_AWVALID,m_axi_gmem3_AWREADY,m_axi_gmem3_WDATA[31:0],m_axi_gmem3_WSTRB[3:0],m_axi_gmem3_WLAST,m_axi_gmem3_WVALID,m_axi_gmem3_WREADY,m_axi_gmem3_BRESP[1:0],m_axi_gmem3_BVALID,m_axi_gmem3_BREADY,m_axi_gmem3_ARADDR[31:0],m_axi_gmem3_ARLEN[7:0],m_axi_gmem3_ARSIZE[2:0],m_axi_gmem3_ARBURST[1:0],m_axi_gmem3_ARLOCK[1:0],m_axi_gmem3_ARREGION[3:0],m_axi_gmem3_ARCACHE[3:0],m_axi_gmem3_ARPROT[2:0],m_axi_gmem3_ARQOS[3:0],m_axi_gmem3_ARVALID,m_axi_gmem3_ARREADY,m_axi_gmem3_RDATA[31:0],m_axi_gmem3_RRESP[1:0],m_axi_gmem3_RLAST,m_axi_gmem3_RVALID,m_axi_gmem3_RREADY,m_axi_gmem4_AWADDR[31:0],m_axi_gmem4_AWLEN[7:0],m_axi_gmem4_AWSIZE[2:0],m_axi_gmem4_AWBURST[1:0],m_axi_gmem4_AWLOCK[1:0],m_axi_gmem4_AWREGION[3:0],m_axi_gmem4_AWCACHE[3:0],m_axi_gmem4_AWPROT[2:0],m_axi_gmem4_AWQOS[3:0],m_axi_gmem4_AWVALID,m_axi_gmem4_AWREADY,m_axi_gmem4_WDATA[31:0],m_axi_gmem4_WSTRB[3:0],m_axi_gmem4_WLAST,m_axi_gmem4_WVALID,m_axi_gmem4_WREADY,m_axi_gmem4_BRESP[1:0],m_axi_gmem4_BVALID,m_axi_gmem4_BREADY,m_axi_gmem4_ARADDR[31:0],m_axi_gmem4_ARLEN[7:0],m_axi_gmem4_ARSIZE[2:0],m_axi_gmem4_ARBURST[1:0],m_axi_gmem4_ARLOCK[1:0],m_axi_gmem4_ARREGION[3:0],m_axi_gmem4_ARCACHE[3:0],m_axi_gmem4_ARPROT[2:0],m_axi_gmem4_ARQOS[3:0],m_axi_gmem4_ARVALID,m_axi_gmem4_ARREADY,m_axi_gmem4_RDATA[31:0],m_axi_gmem4_RRESP[1:0],m_axi_gmem4_RLAST,m_axi_gmem4_RVALID,m_axi_gmem4_RREADY";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "kernel_2mm_wrapper,Vivado 2018.2";
begin
end;
