# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1.xci
# IP: The module: 'zedboard_base_rst_ps7_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1.xci
# IP: The module: 'zedboard_base_rst_ps7_0_200M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/tingyuan/Documents/ddr_check/zedboard-base-master/zedboard_base.xpr/zedboard_base/zedboard_base.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps7_0_200M_1/zedboard_base_rst_ps7_0_200M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps7_0_200M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
