// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module func15 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        A_0_address0,
        A_0_ce0,
        A_0_q0,
        A_1_address0,
        A_1_ce0,
        A_1_q0,
        B_0_address0,
        B_0_ce0,
        B_0_q0,
        B_1_address0,
        B_1_ce0,
        B_1_q0,
        C_0_address0,
        C_0_ce0,
        C_0_q0,
        C_1_address0,
        C_1_ce0,
        C_1_q0,
        C_2_address0,
        C_2_ce0,
        C_2_q0,
        C_3_address0,
        C_3_ce0,
        C_3_q0,
        C_4_address0,
        C_4_ce0,
        C_4_q0,
        C_5_address0,
        C_5_ce0,
        C_5_q0,
        C_6_address0,
        C_6_ce0,
        C_6_q0,
        C_7_address0,
        C_7_ce0,
        C_7_q0,
        D_address0,
        D_ce0,
        D_q0,
        tmp_0_address0,
        tmp_0_ce0,
        tmp_0_we0,
        tmp_0_d0,
        tmp_0_q0,
        tmp_1_address0,
        tmp_1_ce0,
        tmp_1_we0,
        tmp_1_d0,
        tmp_1_q0,
        tmp_2_address0,
        tmp_2_ce0,
        tmp_2_we0,
        tmp_2_d0,
        tmp_2_q0,
        tmp_3_address0,
        tmp_3_ce0,
        tmp_3_we0,
        tmp_3_d0,
        tmp_3_q0,
        tmp_4_address0,
        tmp_4_ce0,
        tmp_4_we0,
        tmp_4_d0,
        tmp_4_q0,
        tmp_5_address0,
        tmp_5_ce0,
        tmp_5_we0,
        tmp_5_d0,
        tmp_5_q0,
        tmp_6_address0,
        tmp_6_ce0,
        tmp_6_we0,
        tmp_6_d0,
        tmp_6_q0,
        tmp_7_address0,
        tmp_7_ce0,
        tmp_7_we0,
        tmp_7_d0,
        tmp_7_q0,
        C_mid_0_address0,
        C_mid_0_ce0,
        C_mid_0_we0,
        C_mid_0_d0,
        C_mid_1_address0,
        C_mid_1_ce0,
        C_mid_1_we0,
        C_mid_1_d0,
        C_mid_2_address0,
        C_mid_2_ce0,
        C_mid_2_we0,
        C_mid_2_d0,
        C_mid_3_address0,
        C_mid_3_ce0,
        C_mid_3_we0,
        C_mid_3_d0,
        C_mid_4_address0,
        C_mid_4_ce0,
        C_mid_4_we0,
        C_mid_4_d0,
        C_mid_5_address0,
        C_mid_5_ce0,
        C_mid_5_we0,
        C_mid_5_d0,
        C_mid_6_address0,
        C_mid_6_ce0,
        C_mid_6_we0,
        C_mid_6_d0,
        C_mid_7_address0,
        C_mid_7_ce0,
        C_mid_7_we0,
        C_mid_7_d0,
        D_mid_address0,
        D_mid_ce0,
        D_mid_we0,
        D_mid_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] A_0_address0;
output   A_0_ce0;
input  [31:0] A_0_q0;
output  [7:0] A_1_address0;
output   A_1_ce0;
input  [31:0] A_1_q0;
output  [7:0] B_0_address0;
output   B_0_ce0;
input  [31:0] B_0_q0;
output  [7:0] B_1_address0;
output   B_1_ce0;
input  [31:0] B_1_q0;
output  [6:0] C_0_address0;
output   C_0_ce0;
input  [31:0] C_0_q0;
output  [6:0] C_1_address0;
output   C_1_ce0;
input  [31:0] C_1_q0;
output  [5:0] C_2_address0;
output   C_2_ce0;
input  [31:0] C_2_q0;
output  [5:0] C_3_address0;
output   C_3_ce0;
input  [31:0] C_3_q0;
output  [5:0] C_4_address0;
output   C_4_ce0;
input  [31:0] C_4_q0;
output  [5:0] C_5_address0;
output   C_5_ce0;
input  [31:0] C_5_q0;
output  [5:0] C_6_address0;
output   C_6_ce0;
input  [31:0] C_6_q0;
output  [5:0] C_7_address0;
output   C_7_ce0;
input  [31:0] C_7_q0;
output  [8:0] D_address0;
output   D_ce0;
input  [31:0] D_q0;
output  [5:0] tmp_0_address0;
output   tmp_0_ce0;
output   tmp_0_we0;
output  [31:0] tmp_0_d0;
input  [31:0] tmp_0_q0;
output  [5:0] tmp_1_address0;
output   tmp_1_ce0;
output   tmp_1_we0;
output  [31:0] tmp_1_d0;
input  [31:0] tmp_1_q0;
output  [4:0] tmp_2_address0;
output   tmp_2_ce0;
output   tmp_2_we0;
output  [31:0] tmp_2_d0;
input  [31:0] tmp_2_q0;
output  [4:0] tmp_3_address0;
output   tmp_3_ce0;
output   tmp_3_we0;
output  [31:0] tmp_3_d0;
input  [31:0] tmp_3_q0;
output  [4:0] tmp_4_address0;
output   tmp_4_ce0;
output   tmp_4_we0;
output  [31:0] tmp_4_d0;
input  [31:0] tmp_4_q0;
output  [4:0] tmp_5_address0;
output   tmp_5_ce0;
output   tmp_5_we0;
output  [31:0] tmp_5_d0;
input  [31:0] tmp_5_q0;
output  [4:0] tmp_6_address0;
output   tmp_6_ce0;
output   tmp_6_we0;
output  [31:0] tmp_6_d0;
input  [31:0] tmp_6_q0;
output  [4:0] tmp_7_address0;
output   tmp_7_ce0;
output   tmp_7_we0;
output  [31:0] tmp_7_d0;
input  [31:0] tmp_7_q0;
output  [6:0] C_mid_0_address0;
output   C_mid_0_ce0;
output   C_mid_0_we0;
output  [31:0] C_mid_0_d0;
output  [6:0] C_mid_1_address0;
output   C_mid_1_ce0;
output   C_mid_1_we0;
output  [31:0] C_mid_1_d0;
output  [5:0] C_mid_2_address0;
output   C_mid_2_ce0;
output   C_mid_2_we0;
output  [31:0] C_mid_2_d0;
output  [5:0] C_mid_3_address0;
output   C_mid_3_ce0;
output   C_mid_3_we0;
output  [31:0] C_mid_3_d0;
output  [5:0] C_mid_4_address0;
output   C_mid_4_ce0;
output   C_mid_4_we0;
output  [31:0] C_mid_4_d0;
output  [5:0] C_mid_5_address0;
output   C_mid_5_ce0;
output   C_mid_5_we0;
output  [31:0] C_mid_5_d0;
output  [5:0] C_mid_6_address0;
output   C_mid_6_ce0;
output   C_mid_6_we0;
output  [31:0] C_mid_6_d0;
output  [5:0] C_mid_7_address0;
output   C_mid_7_ce0;
output   C_mid_7_we0;
output  [31:0] C_mid_7_d0;
output  [8:0] D_mid_address0;
output   D_mid_ce0;
output   D_mid_we0;
output  [31:0] D_mid_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_func1_execute8_fu_66_ap_start;
wire    grp_func1_execute8_fu_66_ap_done;
wire    grp_func1_execute8_fu_66_ap_idle;
wire    grp_func1_execute8_fu_66_ap_ready;
wire   [5:0] grp_func1_execute8_fu_66_tmp_mid_execute_0_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_0_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_0_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_0_d0;
wire   [5:0] grp_func1_execute8_fu_66_tmp_mid_execute_1_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_1_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_1_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_1_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_2_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_2_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_2_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_2_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_3_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_3_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_3_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_3_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_4_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_4_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_4_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_4_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_5_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_5_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_5_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_5_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_6_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_6_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_6_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_6_d0;
wire   [4:0] grp_func1_execute8_fu_66_tmp_mid_execute_7_address0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_7_ce0;
wire    grp_func1_execute8_fu_66_tmp_mid_execute_7_we0;
wire   [31:0] grp_func1_execute8_fu_66_tmp_mid_execute_7_d0;
wire   [7:0] grp_func1_execute8_fu_66_A_0_address0;
wire    grp_func1_execute8_fu_66_A_0_ce0;
wire   [7:0] grp_func1_execute8_fu_66_A_1_address0;
wire    grp_func1_execute8_fu_66_A_1_ce0;
wire   [7:0] grp_func1_execute8_fu_66_B_0_address0;
wire    grp_func1_execute8_fu_66_B_0_ce0;
wire   [7:0] grp_func1_execute8_fu_66_B_1_address0;
wire    grp_func1_execute8_fu_66_B_1_ce0;
wire    grp_buffer_func1_C7_fu_94_ap_start;
wire    grp_buffer_func1_C7_fu_94_ap_done;
wire    grp_buffer_func1_C7_fu_94_ap_idle;
wire    grp_buffer_func1_C7_fu_94_ap_ready;
wire   [6:0] grp_buffer_func1_C7_fu_94_C_input_0_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_0_ce0;
wire   [6:0] grp_buffer_func1_C7_fu_94_C_input_1_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_1_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_2_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_2_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_3_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_3_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_4_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_4_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_5_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_5_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_6_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_6_ce0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_input_7_address0;
wire    grp_buffer_func1_C7_fu_94_C_input_7_ce0;
wire   [6:0] grp_buffer_func1_C7_fu_94_C_mid_0_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_0_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_0_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_0_d0;
wire   [6:0] grp_buffer_func1_C7_fu_94_C_mid_1_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_1_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_1_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_1_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_2_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_2_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_2_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_2_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_3_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_3_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_3_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_3_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_4_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_4_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_4_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_4_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_5_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_5_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_5_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_5_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_6_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_6_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_6_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_6_d0;
wire   [5:0] grp_buffer_func1_C7_fu_94_C_mid_7_address0;
wire    grp_buffer_func1_C7_fu_94_C_mid_7_ce0;
wire    grp_buffer_func1_C7_fu_94_C_mid_7_we0;
wire   [31:0] grp_buffer_func1_C7_fu_94_C_mid_7_d0;
wire    grp_buffer_func1_D6_fu_130_ap_start;
wire    grp_buffer_func1_D6_fu_130_ap_done;
wire    grp_buffer_func1_D6_fu_130_ap_idle;
wire    grp_buffer_func1_D6_fu_130_ap_ready;
wire   [8:0] grp_buffer_func1_D6_fu_130_D_input_address0;
wire    grp_buffer_func1_D6_fu_130_D_input_ce0;
wire   [8:0] grp_buffer_func1_D6_fu_130_D_mid_address0;
wire    grp_buffer_func1_D6_fu_130_D_mid_ce0;
wire    grp_buffer_func1_D6_fu_130_D_mid_we0;
wire   [31:0] grp_buffer_func1_D6_fu_130_D_mid_d0;
reg    grp_func1_execute8_fu_66_ap_start_reg;
reg    ap_block_state1_ignore_call2;
wire    ap_CS_fsm_state2;
reg    grp_buffer_func1_C7_fu_94_ap_start_reg;
reg    ap_block_state1_ignore_call1;
reg    grp_buffer_func1_D6_fu_130_ap_start_reg;
reg    ap_block_state1_ignore_call0;
reg    ap_block_state2_on_subcall_done;
reg   [1:0] ap_NS_fsm;
reg    ap_block_state1;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_func1_execute8_fu_66_ap_start_reg = 1'b0;
#0 grp_buffer_func1_C7_fu_94_ap_start_reg = 1'b0;
#0 grp_buffer_func1_D6_fu_130_ap_start_reg = 1'b0;
end

func1_execute8 grp_func1_execute8_fu_66(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_func1_execute8_fu_66_ap_start),
    .ap_done(grp_func1_execute8_fu_66_ap_done),
    .ap_idle(grp_func1_execute8_fu_66_ap_idle),
    .ap_ready(grp_func1_execute8_fu_66_ap_ready),
    .tmp_mid_execute_0_address0(grp_func1_execute8_fu_66_tmp_mid_execute_0_address0),
    .tmp_mid_execute_0_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_0_ce0),
    .tmp_mid_execute_0_we0(grp_func1_execute8_fu_66_tmp_mid_execute_0_we0),
    .tmp_mid_execute_0_d0(grp_func1_execute8_fu_66_tmp_mid_execute_0_d0),
    .tmp_mid_execute_0_q0(tmp_0_q0),
    .tmp_mid_execute_1_address0(grp_func1_execute8_fu_66_tmp_mid_execute_1_address0),
    .tmp_mid_execute_1_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_1_ce0),
    .tmp_mid_execute_1_we0(grp_func1_execute8_fu_66_tmp_mid_execute_1_we0),
    .tmp_mid_execute_1_d0(grp_func1_execute8_fu_66_tmp_mid_execute_1_d0),
    .tmp_mid_execute_1_q0(tmp_1_q0),
    .tmp_mid_execute_2_address0(grp_func1_execute8_fu_66_tmp_mid_execute_2_address0),
    .tmp_mid_execute_2_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_2_ce0),
    .tmp_mid_execute_2_we0(grp_func1_execute8_fu_66_tmp_mid_execute_2_we0),
    .tmp_mid_execute_2_d0(grp_func1_execute8_fu_66_tmp_mid_execute_2_d0),
    .tmp_mid_execute_2_q0(tmp_2_q0),
    .tmp_mid_execute_3_address0(grp_func1_execute8_fu_66_tmp_mid_execute_3_address0),
    .tmp_mid_execute_3_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_3_ce0),
    .tmp_mid_execute_3_we0(grp_func1_execute8_fu_66_tmp_mid_execute_3_we0),
    .tmp_mid_execute_3_d0(grp_func1_execute8_fu_66_tmp_mid_execute_3_d0),
    .tmp_mid_execute_3_q0(tmp_3_q0),
    .tmp_mid_execute_4_address0(grp_func1_execute8_fu_66_tmp_mid_execute_4_address0),
    .tmp_mid_execute_4_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_4_ce0),
    .tmp_mid_execute_4_we0(grp_func1_execute8_fu_66_tmp_mid_execute_4_we0),
    .tmp_mid_execute_4_d0(grp_func1_execute8_fu_66_tmp_mid_execute_4_d0),
    .tmp_mid_execute_4_q0(tmp_4_q0),
    .tmp_mid_execute_5_address0(grp_func1_execute8_fu_66_tmp_mid_execute_5_address0),
    .tmp_mid_execute_5_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_5_ce0),
    .tmp_mid_execute_5_we0(grp_func1_execute8_fu_66_tmp_mid_execute_5_we0),
    .tmp_mid_execute_5_d0(grp_func1_execute8_fu_66_tmp_mid_execute_5_d0),
    .tmp_mid_execute_5_q0(tmp_5_q0),
    .tmp_mid_execute_6_address0(grp_func1_execute8_fu_66_tmp_mid_execute_6_address0),
    .tmp_mid_execute_6_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_6_ce0),
    .tmp_mid_execute_6_we0(grp_func1_execute8_fu_66_tmp_mid_execute_6_we0),
    .tmp_mid_execute_6_d0(grp_func1_execute8_fu_66_tmp_mid_execute_6_d0),
    .tmp_mid_execute_6_q0(tmp_6_q0),
    .tmp_mid_execute_7_address0(grp_func1_execute8_fu_66_tmp_mid_execute_7_address0),
    .tmp_mid_execute_7_ce0(grp_func1_execute8_fu_66_tmp_mid_execute_7_ce0),
    .tmp_mid_execute_7_we0(grp_func1_execute8_fu_66_tmp_mid_execute_7_we0),
    .tmp_mid_execute_7_d0(grp_func1_execute8_fu_66_tmp_mid_execute_7_d0),
    .tmp_mid_execute_7_q0(tmp_7_q0),
    .A_0_address0(grp_func1_execute8_fu_66_A_0_address0),
    .A_0_ce0(grp_func1_execute8_fu_66_A_0_ce0),
    .A_0_q0(A_0_q0),
    .A_1_address0(grp_func1_execute8_fu_66_A_1_address0),
    .A_1_ce0(grp_func1_execute8_fu_66_A_1_ce0),
    .A_1_q0(A_1_q0),
    .B_0_address0(grp_func1_execute8_fu_66_B_0_address0),
    .B_0_ce0(grp_func1_execute8_fu_66_B_0_ce0),
    .B_0_q0(B_0_q0),
    .B_1_address0(grp_func1_execute8_fu_66_B_1_address0),
    .B_1_ce0(grp_func1_execute8_fu_66_B_1_ce0),
    .B_1_q0(B_1_q0)
);

buffer_func1_C7 grp_buffer_func1_C7_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_buffer_func1_C7_fu_94_ap_start),
    .ap_done(grp_buffer_func1_C7_fu_94_ap_done),
    .ap_idle(grp_buffer_func1_C7_fu_94_ap_idle),
    .ap_ready(grp_buffer_func1_C7_fu_94_ap_ready),
    .C_input_0_address0(grp_buffer_func1_C7_fu_94_C_input_0_address0),
    .C_input_0_ce0(grp_buffer_func1_C7_fu_94_C_input_0_ce0),
    .C_input_0_q0(C_0_q0),
    .C_input_1_address0(grp_buffer_func1_C7_fu_94_C_input_1_address0),
    .C_input_1_ce0(grp_buffer_func1_C7_fu_94_C_input_1_ce0),
    .C_input_1_q0(C_1_q0),
    .C_input_2_address0(grp_buffer_func1_C7_fu_94_C_input_2_address0),
    .C_input_2_ce0(grp_buffer_func1_C7_fu_94_C_input_2_ce0),
    .C_input_2_q0(C_2_q0),
    .C_input_3_address0(grp_buffer_func1_C7_fu_94_C_input_3_address0),
    .C_input_3_ce0(grp_buffer_func1_C7_fu_94_C_input_3_ce0),
    .C_input_3_q0(C_3_q0),
    .C_input_4_address0(grp_buffer_func1_C7_fu_94_C_input_4_address0),
    .C_input_4_ce0(grp_buffer_func1_C7_fu_94_C_input_4_ce0),
    .C_input_4_q0(C_4_q0),
    .C_input_5_address0(grp_buffer_func1_C7_fu_94_C_input_5_address0),
    .C_input_5_ce0(grp_buffer_func1_C7_fu_94_C_input_5_ce0),
    .C_input_5_q0(C_5_q0),
    .C_input_6_address0(grp_buffer_func1_C7_fu_94_C_input_6_address0),
    .C_input_6_ce0(grp_buffer_func1_C7_fu_94_C_input_6_ce0),
    .C_input_6_q0(C_6_q0),
    .C_input_7_address0(grp_buffer_func1_C7_fu_94_C_input_7_address0),
    .C_input_7_ce0(grp_buffer_func1_C7_fu_94_C_input_7_ce0),
    .C_input_7_q0(C_7_q0),
    .C_mid_0_address0(grp_buffer_func1_C7_fu_94_C_mid_0_address0),
    .C_mid_0_ce0(grp_buffer_func1_C7_fu_94_C_mid_0_ce0),
    .C_mid_0_we0(grp_buffer_func1_C7_fu_94_C_mid_0_we0),
    .C_mid_0_d0(grp_buffer_func1_C7_fu_94_C_mid_0_d0),
    .C_mid_1_address0(grp_buffer_func1_C7_fu_94_C_mid_1_address0),
    .C_mid_1_ce0(grp_buffer_func1_C7_fu_94_C_mid_1_ce0),
    .C_mid_1_we0(grp_buffer_func1_C7_fu_94_C_mid_1_we0),
    .C_mid_1_d0(grp_buffer_func1_C7_fu_94_C_mid_1_d0),
    .C_mid_2_address0(grp_buffer_func1_C7_fu_94_C_mid_2_address0),
    .C_mid_2_ce0(grp_buffer_func1_C7_fu_94_C_mid_2_ce0),
    .C_mid_2_we0(grp_buffer_func1_C7_fu_94_C_mid_2_we0),
    .C_mid_2_d0(grp_buffer_func1_C7_fu_94_C_mid_2_d0),
    .C_mid_3_address0(grp_buffer_func1_C7_fu_94_C_mid_3_address0),
    .C_mid_3_ce0(grp_buffer_func1_C7_fu_94_C_mid_3_ce0),
    .C_mid_3_we0(grp_buffer_func1_C7_fu_94_C_mid_3_we0),
    .C_mid_3_d0(grp_buffer_func1_C7_fu_94_C_mid_3_d0),
    .C_mid_4_address0(grp_buffer_func1_C7_fu_94_C_mid_4_address0),
    .C_mid_4_ce0(grp_buffer_func1_C7_fu_94_C_mid_4_ce0),
    .C_mid_4_we0(grp_buffer_func1_C7_fu_94_C_mid_4_we0),
    .C_mid_4_d0(grp_buffer_func1_C7_fu_94_C_mid_4_d0),
    .C_mid_5_address0(grp_buffer_func1_C7_fu_94_C_mid_5_address0),
    .C_mid_5_ce0(grp_buffer_func1_C7_fu_94_C_mid_5_ce0),
    .C_mid_5_we0(grp_buffer_func1_C7_fu_94_C_mid_5_we0),
    .C_mid_5_d0(grp_buffer_func1_C7_fu_94_C_mid_5_d0),
    .C_mid_6_address0(grp_buffer_func1_C7_fu_94_C_mid_6_address0),
    .C_mid_6_ce0(grp_buffer_func1_C7_fu_94_C_mid_6_ce0),
    .C_mid_6_we0(grp_buffer_func1_C7_fu_94_C_mid_6_we0),
    .C_mid_6_d0(grp_buffer_func1_C7_fu_94_C_mid_6_d0),
    .C_mid_7_address0(grp_buffer_func1_C7_fu_94_C_mid_7_address0),
    .C_mid_7_ce0(grp_buffer_func1_C7_fu_94_C_mid_7_ce0),
    .C_mid_7_we0(grp_buffer_func1_C7_fu_94_C_mid_7_we0),
    .C_mid_7_d0(grp_buffer_func1_C7_fu_94_C_mid_7_d0)
);

buffer_func1_D6 grp_buffer_func1_D6_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_buffer_func1_D6_fu_130_ap_start),
    .ap_done(grp_buffer_func1_D6_fu_130_ap_done),
    .ap_idle(grp_buffer_func1_D6_fu_130_ap_idle),
    .ap_ready(grp_buffer_func1_D6_fu_130_ap_ready),
    .D_input_address0(grp_buffer_func1_D6_fu_130_D_input_address0),
    .D_input_ce0(grp_buffer_func1_D6_fu_130_D_input_ce0),
    .D_input_q0(D_q0),
    .D_mid_address0(grp_buffer_func1_D6_fu_130_D_mid_address0),
    .D_mid_ce0(grp_buffer_func1_D6_fu_130_D_mid_ce0),
    .D_mid_we0(grp_buffer_func1_D6_fu_130_D_mid_we0),
    .D_mid_d0(grp_buffer_func1_D6_fu_130_D_mid_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_buffer_func1_C7_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_buffer_func1_C7_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_buffer_func1_C7_fu_94_ap_ready == 1'b1)) begin
            grp_buffer_func1_C7_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_buffer_func1_D6_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_buffer_func1_D6_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_buffer_func1_D6_fu_130_ap_ready == 1'b1)) begin
            grp_buffer_func1_D6_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_func1_execute8_fu_66_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_func1_execute8_fu_66_ap_start_reg <= 1'b1;
        end else if ((grp_func1_execute8_fu_66_ap_ready == 1'b1)) begin
            grp_func1_execute8_fu_66_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_0_address0 = grp_func1_execute8_fu_66_A_0_address0;

assign A_0_ce0 = grp_func1_execute8_fu_66_A_0_ce0;

assign A_1_address0 = grp_func1_execute8_fu_66_A_1_address0;

assign A_1_ce0 = grp_func1_execute8_fu_66_A_1_ce0;

assign B_0_address0 = grp_func1_execute8_fu_66_B_0_address0;

assign B_0_ce0 = grp_func1_execute8_fu_66_B_0_ce0;

assign B_1_address0 = grp_func1_execute8_fu_66_B_1_address0;

assign B_1_ce0 = grp_func1_execute8_fu_66_B_1_ce0;

assign C_0_address0 = grp_buffer_func1_C7_fu_94_C_input_0_address0;

assign C_0_ce0 = grp_buffer_func1_C7_fu_94_C_input_0_ce0;

assign C_1_address0 = grp_buffer_func1_C7_fu_94_C_input_1_address0;

assign C_1_ce0 = grp_buffer_func1_C7_fu_94_C_input_1_ce0;

assign C_2_address0 = grp_buffer_func1_C7_fu_94_C_input_2_address0;

assign C_2_ce0 = grp_buffer_func1_C7_fu_94_C_input_2_ce0;

assign C_3_address0 = grp_buffer_func1_C7_fu_94_C_input_3_address0;

assign C_3_ce0 = grp_buffer_func1_C7_fu_94_C_input_3_ce0;

assign C_4_address0 = grp_buffer_func1_C7_fu_94_C_input_4_address0;

assign C_4_ce0 = grp_buffer_func1_C7_fu_94_C_input_4_ce0;

assign C_5_address0 = grp_buffer_func1_C7_fu_94_C_input_5_address0;

assign C_5_ce0 = grp_buffer_func1_C7_fu_94_C_input_5_ce0;

assign C_6_address0 = grp_buffer_func1_C7_fu_94_C_input_6_address0;

assign C_6_ce0 = grp_buffer_func1_C7_fu_94_C_input_6_ce0;

assign C_7_address0 = grp_buffer_func1_C7_fu_94_C_input_7_address0;

assign C_7_ce0 = grp_buffer_func1_C7_fu_94_C_input_7_ce0;

assign C_mid_0_address0 = grp_buffer_func1_C7_fu_94_C_mid_0_address0;

assign C_mid_0_ce0 = grp_buffer_func1_C7_fu_94_C_mid_0_ce0;

assign C_mid_0_d0 = grp_buffer_func1_C7_fu_94_C_mid_0_d0;

assign C_mid_0_we0 = grp_buffer_func1_C7_fu_94_C_mid_0_we0;

assign C_mid_1_address0 = grp_buffer_func1_C7_fu_94_C_mid_1_address0;

assign C_mid_1_ce0 = grp_buffer_func1_C7_fu_94_C_mid_1_ce0;

assign C_mid_1_d0 = grp_buffer_func1_C7_fu_94_C_mid_1_d0;

assign C_mid_1_we0 = grp_buffer_func1_C7_fu_94_C_mid_1_we0;

assign C_mid_2_address0 = grp_buffer_func1_C7_fu_94_C_mid_2_address0;

assign C_mid_2_ce0 = grp_buffer_func1_C7_fu_94_C_mid_2_ce0;

assign C_mid_2_d0 = grp_buffer_func1_C7_fu_94_C_mid_2_d0;

assign C_mid_2_we0 = grp_buffer_func1_C7_fu_94_C_mid_2_we0;

assign C_mid_3_address0 = grp_buffer_func1_C7_fu_94_C_mid_3_address0;

assign C_mid_3_ce0 = grp_buffer_func1_C7_fu_94_C_mid_3_ce0;

assign C_mid_3_d0 = grp_buffer_func1_C7_fu_94_C_mid_3_d0;

assign C_mid_3_we0 = grp_buffer_func1_C7_fu_94_C_mid_3_we0;

assign C_mid_4_address0 = grp_buffer_func1_C7_fu_94_C_mid_4_address0;

assign C_mid_4_ce0 = grp_buffer_func1_C7_fu_94_C_mid_4_ce0;

assign C_mid_4_d0 = grp_buffer_func1_C7_fu_94_C_mid_4_d0;

assign C_mid_4_we0 = grp_buffer_func1_C7_fu_94_C_mid_4_we0;

assign C_mid_5_address0 = grp_buffer_func1_C7_fu_94_C_mid_5_address0;

assign C_mid_5_ce0 = grp_buffer_func1_C7_fu_94_C_mid_5_ce0;

assign C_mid_5_d0 = grp_buffer_func1_C7_fu_94_C_mid_5_d0;

assign C_mid_5_we0 = grp_buffer_func1_C7_fu_94_C_mid_5_we0;

assign C_mid_6_address0 = grp_buffer_func1_C7_fu_94_C_mid_6_address0;

assign C_mid_6_ce0 = grp_buffer_func1_C7_fu_94_C_mid_6_ce0;

assign C_mid_6_d0 = grp_buffer_func1_C7_fu_94_C_mid_6_d0;

assign C_mid_6_we0 = grp_buffer_func1_C7_fu_94_C_mid_6_we0;

assign C_mid_7_address0 = grp_buffer_func1_C7_fu_94_C_mid_7_address0;

assign C_mid_7_ce0 = grp_buffer_func1_C7_fu_94_C_mid_7_ce0;

assign C_mid_7_d0 = grp_buffer_func1_C7_fu_94_C_mid_7_d0;

assign C_mid_7_we0 = grp_buffer_func1_C7_fu_94_C_mid_7_we0;

assign D_address0 = grp_buffer_func1_D6_fu_130_D_input_address0;

assign D_ce0 = grp_buffer_func1_D6_fu_130_D_input_ce0;

assign D_mid_address0 = grp_buffer_func1_D6_fu_130_D_mid_address0;

assign D_mid_ce0 = grp_buffer_func1_D6_fu_130_D_mid_ce0;

assign D_mid_d0 = grp_buffer_func1_D6_fu_130_D_mid_d0;

assign D_mid_we0 = grp_buffer_func1_D6_fu_130_D_mid_we0;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call2 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_buffer_func1_D6_fu_130_ap_done == 1'b0) | (grp_buffer_func1_C7_fu_94_ap_done == 1'b0) | (grp_func1_execute8_fu_66_ap_done == 1'b0));
end

assign grp_buffer_func1_C7_fu_94_ap_start = grp_buffer_func1_C7_fu_94_ap_start_reg;

assign grp_buffer_func1_D6_fu_130_ap_start = grp_buffer_func1_D6_fu_130_ap_start_reg;

assign grp_func1_execute8_fu_66_ap_start = grp_func1_execute8_fu_66_ap_start_reg;

assign tmp_0_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_0_address0;

assign tmp_0_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_0_ce0;

assign tmp_0_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_0_d0;

assign tmp_0_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_0_we0;

assign tmp_1_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_1_address0;

assign tmp_1_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_1_ce0;

assign tmp_1_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_1_d0;

assign tmp_1_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_1_we0;

assign tmp_2_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_2_address0;

assign tmp_2_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_2_ce0;

assign tmp_2_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_2_d0;

assign tmp_2_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_2_we0;

assign tmp_3_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_3_address0;

assign tmp_3_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_3_ce0;

assign tmp_3_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_3_d0;

assign tmp_3_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_3_we0;

assign tmp_4_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_4_address0;

assign tmp_4_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_4_ce0;

assign tmp_4_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_4_d0;

assign tmp_4_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_4_we0;

assign tmp_5_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_5_address0;

assign tmp_5_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_5_ce0;

assign tmp_5_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_5_d0;

assign tmp_5_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_5_we0;

assign tmp_6_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_6_address0;

assign tmp_6_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_6_ce0;

assign tmp_6_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_6_d0;

assign tmp_6_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_6_we0;

assign tmp_7_address0 = grp_func1_execute8_fu_66_tmp_mid_execute_7_address0;

assign tmp_7_ce0 = grp_func1_execute8_fu_66_tmp_mid_execute_7_ce0;

assign tmp_7_d0 = grp_func1_execute8_fu_66_tmp_mid_execute_7_d0;

assign tmp_7_we0 = grp_func1_execute8_fu_66_tmp_mid_execute_7_we0;

endmodule //func15
